version: '2'

services:
 ovs1:
  image: jhershbe/centos7-ovs-dual-nic:latest
  ports:
    - "6641:6640"
  command: "/usr/bin/supervisord -n"
  privileged: true
  networks:
   mgmt:
    ipv4_address: 172.28.5.11
   external:
    ipv4_address: 172.29.5.11
 ovs2:
  image: jhershbe/centos7-ovs-dual-nic:latest
  ports:
    - "6642:6640"
  command: "/usr/bin/supervisord -n"
  privileged: true
  networks:
   mgmt:
    ipv4_address: 172.28.5.12
   external:
    ipv4_address: 172.29.5.12

networks:
 mgmt:
  driver: bridge
  ipam:
   config:
    - subnet: 172.28.0.0/16
      ip_range: 172.28.5.0/24
      gateway: 172.28.5.254
 external:
  driver: bridge
  ipam:
   config:
    - subnet: 172.29.0.0/16
      ip_range: 172.29.5.0/24
      gateway: 172.29.5.254
