/*
* Generated file
*
* Generated from: yang module name: netvirt-impl yang module local name: netvirt-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri May 01 12:16:10 EDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.netvirt.impl;

import org.osgi.framework.BundleContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class NetVirtImplModuleFactory extends org.opendaylight.controller.config.yang.config.netvirt.impl.AbstractNetVirtImplModuleFactory {

    private static final Logger logger = LoggerFactory.getLogger(NetVirtImplModuleFactory.class);

    @Override
    public Module createModule(String instanceName,
            DependencyResolver dependencyResolver,
            DynamicMBeanWithInstance old, BundleContext bundleContext)
            throws Exception {
        Module netVirtModule =  super.createModule(instanceName, dependencyResolver, old, bundleContext);
        setModuleBundleContext(bundleContext, netVirtModule);
        return netVirtModule;
    }

    @Override
    public Module createModule(String instanceName,
            DependencyResolver dependencyResolver, BundleContext bundleContext) {
        Module netVirtModule = super.createModule(instanceName, dependencyResolver, bundleContext);
        setModuleBundleContext(bundleContext, netVirtModule);
        return netVirtModule;
    }
    
    private void setModuleBundleContext(BundleContext bundleContext,
            Module netVirtModule) {
        if(netVirtModule instanceof NetVirtImplModule) {
            ((NetVirtImplModule) netVirtModule).setBundleContext(bundleContext);
        } else {
            logger.warn("Module is of type {} expected type {}",
                    netVirtModule.getClass(),
                    NetVirtImplModule.class);
        }
    }
}
