
## RENAME THIS FILE TO local.conf BEFORE USING IT IN THE COMPUTE NODE##

[[local|localrc]]
LOGFILE=stack.sh.log
OFFLINE=true
#RECLONE=yes
disable_all_services
#enable_service n-cpu quantum q-agt n-novnc qpid
enable_service neutron nova n-cpu quantum q-agt n-novnc qpid
 
HOST_NAME=fedora2
HOST_IP=192.168.56.102
SERVICE_HOST_NAME=fedora1
SERVICE_HOST=192.168.56.101

FLOATING_RANGE=192.168.100.0/24

Q_PLUGIN=ml2
#Q_ML2_TENANT_NETWORK_TYPE=vlan
#ENABLE_TENANT_VLANS=True
Q_ML2_TENANT_NETWORK_TYPE=vxlan
Q_AGENT_EXTRA_AGENT_OPTS=(tunnel_types=vxlan)
Q_ML2_PLUGIN_MECHANISM_DRIVERS=opendaylight,logger
NEUTRON_REPO=https://github.com/CiscoSystems/neutron.git
NEUTRON_BRANCH=odl_ml2

#Q_PLUGIN=ml2
#Q_AGENT=openvswitch
#Q_ML2_PLUGIN_MECHANISM_DRIVERS=openvswitch,linuxbridge,l2population
#Q_AGENT_EXTRA_AGENT_OPTS=(tunnel_types=gre)
#Q_AGENT_EXTRA_SRV_OPTS=(local_ip=$HOST_IP)

Q_HOST=$SERVICE_HOST
MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOSTPORT=$SERVICE_HOST:9292
KEYSTONE_AUTH_HOST=$SERVICE_HOST
KEYSTONE_SERVICE_HOST=$SERVICE_HOST
 
MYSQL_PASSWORD=mysql
RABBIT_PASSWORD=rabbit
QPID_PASSWORD=rabbit
SERVICE_TOKEN=service
SERVICE_PASSWORD=admin
ADMIN_PASSWORD=admin

LOGFILE=/opt/stack/logs/stack.sh.log
VERBOSE=True
LOG_COLOR=False
SCREEN_LOGDIR=/opt/stack/logs
EXTRA_OPTS=(scheduler_default_filters=AllHostsFilter)

[[post-config|/etc/neutron/plugins/ml2/ml2_conf.ini]]
[ml2_odl]
url=http://192.168.56.1:8080/controller/nb/v2/neutron
username=admin
password=admin
