/*
* Generated file
*
* Generated from: yang module name: ovssfc-provider-impl yang module local name: ovssfc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Aug 11 13:45:11 EDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.ovssfc_provider.impl;
public class OvsSfcProviderModuleFactory extends org.opendaylight.controller.config.yang.config.ovssfc_provider.impl.AbstractOvsSfcProviderModuleFactory {

}
